version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - $PWD/webroot:/webroot
      - $PWD/docker-conf/nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql
  php:
    image: thinkphp_php:latest
    volumes:
      - $PWD/webroot:/webroot
  mysql:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - $PWD/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "cG50bWRjZy53cA=="